refresh_device:
  name: Refresh Device
  description: Refresh data for a specific GOBZIGH device
  fields:
    device_id:
      name: Device ID
      description: The MAC address/device ID of the GOBZIGH device
      required: true
      selector:
        text:

control_relay:
  name: Control Relay
  description: Control the relay state of a GOBZIGH device
  fields:
    device_id:
      name: Device ID
      description: The MAC address/device ID of the GOBZIGH device
      required: true
      selector:
        text:
    state:
      name: State
      description: Turn relay on or off
      required: true
      selector:
        boolean:
